### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by louis77** [neyestrabelli/xml-formatter#24]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [xml-formatter](https://github.com/neyestrabelli/xml-formatter) package, v0.9.1

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:770

RangeError: Maximum call stack size exceeded
    at module.exports.spliceArray (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/helpers.js:20:32)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:623:7)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:550:12)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:534:26
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:765:18)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:532:21)
    at TextBuffer.module.exports.TextBuffer.setText (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:472:19)
    at TextEditor.module.exports.TextEditor.setText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:707:26)
    at Object.module.exports.indent (/Users/louis77/.atom/packages/xml-formatter/lib/xml-formatter.coffee:84:14)
    at atom-workspace.<anonymous> (/Users/louis77/.atom/packages/xml-formatter/lib/xml-formatter.coffee:22:69)
```

### Commands

```
     -0:31.9.0 application:new-file (atom-text-editor.editor.is-focused)
     -0:31.4.0 core:paste (atom-text-editor.editor.is-focused)
     -0:30.2.0 core:undo (atom-text-editor.editor.is-focused)
     -0:19.9.0 core:paste (atom-text-editor.editor.is-focused)
     -0:09.8.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  3x -0:07.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:06.8.0 command-palette:toggle (atom-text-editor.editor.mini.is-focused)
     -0:04.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.3.0 xml-formatter:indent (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
pretty-json, v0.4.1
xml-formatter, v0.9.1

# Dev
No dev packages
```

**Comment by RoyalPulp** [comment]
Same problem here, with a 3MB XML File (*.tcx)
As the Issue was closed in July 2016, is there a solution?
Have a nice day, Hendrik


[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.10
**Thrown From**: [xml-formatter](https://github.com/neyestrabelli/xml-formatter) package 0.10.0


### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:824

RangeError: Maximum call stack size exceeded
    at Object.spliceWithArray (/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:362:46)
    at TokenizedBuffer.module.exports.TokenizedBuffer.bufferDidChange (/app.asar/src/tokenized-buffer.js:278:18)
    at /app.asar/node_modules/text-buffer/lib/text-buffer.js:671:36
    at Set.forEach (native)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (/app.asar/node_modules/text-buffer/lib/text-buffer.js:670:33)
    at TextBuffer.module.exports.TextBuffer.applyChange (/app.asar/node_modules/text-buffer/lib/text-buffer.js:664:12)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/app.asar/node_modules/text-buffer/lib/text-buffer.js:557:19)
    at /app.asar/node_modules/text-buffer/lib/text-buffer.js:538:26
    at TextBuffer.module.exports.TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:819:18)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/app.asar/node_modules/text-buffer/lib/text-buffer.js:536:21)
    at TextBuffer.module.exports.TextBuffer.setText (/app.asar/node_modules/text-buffer/lib/text-buffer.js:476:19)
    at TextEditor.module.exports.TextEditor.setText (/app.asar/src/text-editor.js:1070:26)
    at Object.indent (/packages/xml-formatter/lib/xml-formatter.coffee:86:65)
    at /packages/xml-formatter/lib/xml-formatter.coffee:22:69)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1170:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:333:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -7:53.2.0 command-palette:toggle (input.hidden-input)
     -7:49.2.0 core:confirm (input.hidden-input)
     -7:49.2.0 settings-view:open (input.hidden-input)
     -7:43.3.0 core:confirm (input.hidden-input)
     -7:38.6.0 core:select-all (input.hidden-input)
     -7:35.8.0 core:confirm (input.hidden-input)
     -7:33.8.0 core:select-all (input.hidden-input)
     -7:32.6.0 core:confirm (input.hidden-input)
     -6:16.5.0 xml-formatter:indent (div.line)
```

### Non-Core Packages

```
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-meld 0.3.3 
atom-php-navigation 0.6.0 
atom-silverstripe 2.8.0 
autoclose-html 0.23.0 
composer 0.5.0 
docblockr 0.9.1 
emmet 2.4.3 
git-diff-details 1.4.0 
git-plus 7.3.3 
git-projects 1.17.0 
git-status 0.3.4 
git-time-machine 1.5.6 
linter 1.11.23 
linter-php 1.3.1 
minimap 4.26.8 
minimap-git-diff 4.3.1 
php-debug 0.2.4 
pigments 0.39.0 
project-manager 3.3.3 
silverstripe-bundle 0.3.0 
tree-view-git-status 1.3.1 
xml-formatter 0.10.0 
```
